FROM pytorch/torchserve:latest

USER root

RUN mkdir -p model-weights/ \
    && curl -o model-weights/sam_vit_h_4b8939.pth https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth

RUN mkdir -p model-weights/ \
    && curl -o model-weights/sam_vit_h_4b8939.pth https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth

RUN pip install "onnxruntime==1.14.1" "onnx==1.13.1" "git+https://github.com/facebookresearch/segment-anything.git#567662b" awscli

RUN mkdir -p /home/model-server/

COPY ./deployment/config_decode.properties /home/model-server/config.properties

COPY ./deployment/append_memory_setting.sh /home/model-server/append_memory_setting.sh

RUN chmod +x /home/model-server/append_memory_setting.sh

RUN /home/model-server/append_memory_setting.sh

COPY handler*.py ./

RUN torch-model-archiver --model-name sam_vit_h_encode --version 1.0.0 --serialized-file model-weights/sam_vit_h_4b8939.pth --handler handler_encode.py

COPY scripts ./scripts

RUN python scripts/export_onnx_model.py --checkpoint model-weights/sam_vit_h_4b8939.pth --model-type vit_h --output sam_vit_h_decode.onnx

RUN torch-model-archiver --model-name sam_vit_h_decode --version 1.0.0 --serialized-file sam_vit_h_decode.onnx --handler handler_decode.py

RUN mv *.mar model-store/ \
    && rm *.onnx \
    && rm -rf model-weights

WORKDIR /home/model-server

# .mar files copied to s3 in gh action