version: '3.4'
services:
  dev:
    image: developmentseed/sam-dev:v1
    build:
      context: .
      dockerfile: Dockerfile-dev
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    ports:
      - '8888:8888'
    volumes:
      - ./:/segment-anything-services
  build:
    image: developmentseed/sam-build:latest
    build:
      context: .
      dockerfile: Dockerfile-build
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    command: "/bin/bash -c '
      set -x
      mkdir -p /home/segment-anything-service/model-weights/ &&
      cp /workspace/model-weights/* /home/segment-anything-service/model-weights &&
      cp /workspace/sam_* /home/segment-anything-service/model-store/'"
    volumes:
      - ./:/home/segment-anything-service
    working_dir: /home/segment-anything-service
  cpu:
    image: developmentseed/sam-cpu:latest
    build:
      context: .
      dockerfile: Dockerfile-cpu
    ports:
      - '7080:7080'
    volumes:
      - ./:/home/segment-anything-service
      - ./model-store:/home/model-server/volume/model-store
    working_dir: /home/segment-anything-service
    command: "/bin/bash -c '
      set -x
      ./deployment/append_memory_setting.sh &&
      torchserve --foreground --ts-config ./deployment/config_decode.properties'"
    depends_on:
      - build
  gpu:
    image: developmentseed/sam-gpu:latest
    build:
      context: .
      dockerfile: Dockerfile-gpu
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    ports:
      - '8080:8080'
    volumes:
      - ./:/home/segment-anything-service
      - ./model-store:/home/model-server/volume/model-store
    working_dir: /home/segment-anything-service
    command: "/bin/bash -c '
      set -x
      ./deployment/append_memory_setting.sh &&
      torchserve --foreground --ts-config ./deployment/config_encode.properties'"
    depends_on:
      - build
