name: segment-geo
channels:
    - conda-forge
    - pytorch
    - nvidia
dependencies:
    - httpx
    - ipykernel
    - matplotlib
    - gcc
    - opencv
    - onnx
    - onnxruntime
    - pandas
    - pillow
    - pip
    - pytorch-cuda==11.7
    - pystac-client
    - rasterio
    - scikit-image
    - tensorboard
    - pip:
        - git+https://github.com/facebookresearch/segment-anything.git
        - pycocotools
        - torch==2.0
        - pytorch-lightning==2.0
        - torchvision
        - matplotlib
        - planetary-computer
        - pystac
        - pystac-client
        - streamlit
        - streamlit-image-coordinates
        - mercantile