#! /bin/bash
set -xeuo pipefail

mkdir -p /home/model-server/volume/model-store || true
mkdir -p /home/model-server/volume/tmp || true

aws s3 cp s3://segment-anything-services-prod-685980093638-us-east-1/${GitSha}/ ./volume/model-store/ --recursive

torchserve --foreground --ts-config ./config.properties

